<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="44451" started-at="2021-04-01T07:26:45Z" finished-at="2021-04-01T07:27:29Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="44451" started-at="2021-04-01T07:26:45Z" finished-at="2021-04-01T07:27:29Z">
      <class name="com.Test.GW_BillingCenter_Test1">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.Test.GW_BillingCenter_Test1@2b6856dd]" name="setUp" is-config="true" duration-ms="5609" started-at="2021-04-01T12:56:45Z" finished-at="2021-04-01T12:56:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="BillingTest()[pri:0, instance:com.Test.GW_BillingCenter_Test1@2b6856dd]" name="BillingTest" duration-ms="37909" started-at="2021-04-01T12:56:51Z" finished-at="2021-04-01T12:57:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [11] but found [12]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [11] but found [12]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.pages.Sandbox.GW_BillingCenter_Resuables.bc_AccountSummary_Invoices(GW_BillingCenter_Resuables.java:228)
	at com.Test.GW_BillingCenter_Test1.BillingTest(GW_BillingCenter_Test1.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BillingTest -->
        <test-method status="PASS" signature="Closure()[pri:0, instance:com.Test.GW_BillingCenter_Test1@2b6856dd]" name="Closure" is-config="true" duration-ms="778" started-at="2021-04-01T12:57:29Z" finished-at="2021-04-01T12:57:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Closure -->
      </class> <!-- com.Test.GW_BillingCenter_Test1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
